### ISSUE TITLE
CSS Issue with Host with Long Names 

### ISSUE THREAD

**Issue by vallieres** [firesidelabs/fireside#82]
Yup, that's me :P

![Long names](https://d17oy1vhnax1f7.cloudfront.net/items/1q2Q2q0g0l0W350p3C3y/Image%202017-01-26%20at%201.27.35%20PM.png?v=406604ca)

Long names makes the "PODCASTNAME on social media" have a margin to the left.

https://rgba.fireside.fm/

**Comment by CameronBanga** [comment]
Was just about the add the same ticket. Here's my screenshot.

![screen shot 2017-01-26 at 9 24 05 pm](https://cloud.githubusercontent.com/assets/611354/22359556/fb0e538c-e40d-11e6-9319-5fe1b8c7ed26.png)

**Comment by dan** [comment]
@bynines Should be fixable?

**Comment by bynines** [comment]
@dan, yes. This has been resolved in 4c3f01d0

**Comment by vallieres** [comment]
Actually I still have issue with my super long last name :P 
http://www.rgba.fm/

**Comment by bynines** [comment]
@vallieres The close of the issue was pre-deployment, so, while you weren't able to see in production, it was "on it's way to you." If you check it now, it should no longer be an issue as this has been deployed.

**Comment by vallieres** [comment]
Thanks! :D PERFECT!
